version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  SonarQube_Token:
    secure: j85zlcsESyK89jZFUeRdb0WP+5ACzMn4F/1Rmaun7NENBlkdtR0j3PBFIpdeY6pn
before_build:
- cmd: dotnet restore
- cmd: choco install "msbuild-sonarqube-runner" -y
- cmd: MSBuild.SonarQube.Runner.exe begin /k:"divisors-master" /n:"Divisors" /v:"1.1.3" /d:sonar.host.url=https://sonarqube.com /d:sonar.login=%SonarQube_Token% /d:"sonar.organization=mstama-github"
build:
  verbosity: minimal
after_build:
- cmd: MSBuild.SonarQube.Runner.exe end /d:sonar.login=%SonarQube_Token%
test_script:
- cmd: dotnet test .\UnitTests\UnitTests.csproj
skip_commits:
  files:
    - '**/*.md'
    - '**/*.txt'
    - '**/*.yml'
